"""Tool registry: groups and aliases for system prompt."""

TOOL_GROUPS = {
    "account": [
        "ensure_user",
        "show_account",
        "get_my_profile",
        "update_profile",
        "get_esid",
    ],
    "user_input": [
        "start_planning_widget",
        "save_onboarding_step",
        "submit_onboarding",
        "save_onboarding_stage",
        "check_form_progress",
        "handle_greeting",
        "show_stage2_widget",
        "show_stage3_widget",
        "show_profile_widget",
        "collect_academic_profile",
        "collect_exam_scores",
        "collect_research_profile",
        "collect_work_experience",
        "collect_extracurriculars",
        "collect_financial_profile",
        "collect_preferences",
        "generate_candidate_score",
        "check_profile_ready",
    ],
    "uni_research": [
        "search_universities",
        "match_universities",
        "get_university_detail",
        "get_program_detail",
        "compare_universities",
        "add_university_to_plan",
        "remove_university",
        "get_universities",
        "show_university_basket",
    ],
    "documents": [
        "generate_resume_draft",
        "get_resume",
        "update_resume_section",
        "generate_sop_outline",
        "generate_lor_guide",
        "save_document",
        "analyze_document",
    ],
    "planning": [
        "create_study_plan",
        "get_study_plan",
        "list_study_plans",
        "add_task",
        "get_tasks",
        "complete_task",
        "add_calendar_event",
        "get_calendar_events",
    ],
    "linking": [
        "create_link_code",
        "show_dashboard",
        "subscribe_college_notification",
        "get_college_subscriptions",
        "unsubscribe_college",
    ],
}

TOOL_ALIASES = {
    "init": "ensure_user",
    "whoami": "get_my_profile",
    "account": "show_account",
    "my_id": "show_account",
    "profile": "get_my_profile",
    "onboard": "start_planning_widget",
    "begin": "start_planning_widget",
    "start": "start_planning_widget",
    "academics": "collect_academic_profile",
    "exams": "collect_exam_scores",
    "research": "collect_research_profile",
    "find_unis": "search_universities",
    "match": "match_universities",
    "shortlist": "add_university_to_plan",
    "basket": "show_university_basket",
    "make_resume": "generate_resume_draft",
    "cv": "generate_resume_draft",
    "dashboard": "show_dashboard",
    "home": "show_dashboard",
    "notify": "subscribe_college_notification",
}
